# Generated by Django 3.0.2 on 2020-01-24 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('slug', models.TextField(max_length=255)),
                ('uuid', models.TextField(max_length=255)),
            ],
        ),
    ]
