# Generated by Django 3.0.2 on 2020-01-27 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmation_code', models.TextField(max_length=20)),
                ('product_name', models.TextField(max_length=255)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('product_cost', models.DecimalField(decimal_places=2, max_digits=20)),
                ('quantity', models.IntegerField()),
                ('customer_name', models.TextField(max_length=255)),
                ('customer_email', models.EmailField(max_length=255)),
                ('customer_phone', models.TextField(max_length=255)),
            ],
        ),
    ]
